### ISSUE TITLE
Doesn't work with Taylor & Francis Group website

### ISSUE THREAD

**Issue by anarfred** [nfahlgren/scihub_bookmark#1]
I've a problem using your bookmarklet with the [Taylor & Francis Group website](http://www.tandfonline.com/). The resulting adress after using the bookmarklet seems cropped, as you can see with this exemple : before using the bookmarklet : [http://www.tandfonline.com/doi/abs/10.1080/00043079.1991.10786750?journalCode=rcab20](url) and after using it : [http://www.tandfonline.com.sci-hub.io/doi/abs/10.1080](url).

**Comment by nfahlgren** [comment]
Thanks @anarfred
